### ISSUE TITLE
Gantt-2

### ISSUE THREAD

**Issue by gitllama** [gitllama/Pages#3]
Gantt Test

```yaml
A: 
  start_date : 2020-10-16
  end_date : 2020-11-05
B: 
  start_date : 2020-11-15
  end_date : 2020-11-26
```
